-- MySQL Script generated by MySQL Workbench
-- 10/24/14 16:27:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idclie` INT(5) NOT NULL COMMENT 'Primary key tabla ClienteId',
  `rut` INT(8) NULL DEFAULT NULL COMMENT 'Rut cliente',
  `dv` CHAR(1) NULL DEFAULT NULL COMMENT 'Dígito verificador cliente',
  `nomb` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Nombres de cliente',
  `apells` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Apellidos del cliente',
  `fenac` DATE NULL DEFAULT NULL COMMENT 'Fecha nacimiento del cliente',
  `fevalde` DATE NULL DEFAULT NULL COMMENT 'Fecha de activación del cliente',
  `Correo` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Correo electronico Cliente',
  PRIMARY KEY (`idclie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `idemp` INT(5) NOT NULL COMMENT 'Primary key ID de la empresa',
  `rutemp` INT(8) NULL DEFAULT NULL COMMENT 'Numero identificador de la empresa rut',
  `dvemp` CHAR(1) NULL DEFAULT NULL COMMENT 'Dígito verificador Empresa',
  `nomb` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Nombre Empresa',
  `fenac` DATE NULL DEFAULT NULL COMMENT 'Fecha de inicio de actividades',
  `fevalde` DATE NULL DEFAULT NULL COMMENT 'Fecha de activación empresa en el sistema',
  `Cliente_idclie` INT(5) NOT NULL COMMENT 'Foreing key tabla cliente',
  PRIMARY KEY (`idemp`),
  INDEX `fk_Empresa_Cliente1_idx` (`Cliente_idclie` ASC),
  CONSTRAINT `fk_Empresa_Cliente1`
    FOREIGN KEY (`Cliente_idclie`)
    REFERENCES `mydb`.`Cliente` (`idclie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estados` (
  `idest` INT(5) NOT NULL COMMENT 'Primary key Id estado',
  `nomest` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Nombre de estado',
  `descest` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Descripcion  del estado',
  PRIMARY KEY (`idest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idus` INT(5) NOT NULL COMMENT 'Primary key tabla usuario',
  `usernom` VARCHAR(8) NULL DEFAULT NULL COMMENT 'Nombre Usuario para acceder',
  `cod` VARCHAR(8) NULL DEFAULT NULL COMMENT 'Clave de usuario para acceder',
  `nomb` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Nombres del usuario',
  `Apells` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Apellidos del Usuario',
  `fecrea` DATE NULL DEFAULT NULL COMMENT 'Fecha de creación del Usuario',
  `fevalha` DATE NULL DEFAULT NULL COMMENT 'Fecha de expiración de cuenta',
  `Estados_idest` INT(5) NOT NULL COMMENT 'Foring key yalba estados',
  PRIMARY KEY (`idus`),
  INDEX `fk_Usuario_Estados1_idx` (`Estados_idest` ASC),
  CONSTRAINT `fk_Usuario_Estados1`
    FOREIGN KEY (`Estados_idest`)
    REFERENCES `mydb`.`Estados` (`idest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `idpais` INT NOT NULL COMMENT 'Primary key Id del pais',
  `nompais` VARCHAR(45) NOT NULL COMMENT 'Nombre pais',
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Region` (
  `idregion` INT NOT NULL COMMENT 'Primary key Id de la region',
  `nomregion` VARCHAR(75) NULL DEFAULT NULL COMMENT 'Nombre de la region',
  `Pais_idpais` INT NOT NULL COMMENT 'Foreing key tabla pais',
  PRIMARY KEY (`idregion`),
  INDEX `fk_Region_Pais1_idx` (`Pais_idpais` ASC),
  CONSTRAINT `fk_Region_Pais1`
    FOREIGN KEY (`Pais_idpais`)
    REFERENCES `mydb`.`Pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ciudad` (
  `idciu` INT NOT NULL COMMENT 'Primary key Id de la ciudad',
  `nomciu` VARCHAR(75) NULL DEFAULT NULL COMMENT 'Nombre de la ciudad',
  `Region_idregion` INT NOT NULL COMMENT 'Foreing key tabla region',
  PRIMARY KEY (`idciu`),
  INDEX `fk_Ciudad_Region1_idx` (`Region_idregion` ASC),
  CONSTRAINT `fk_Ciudad_Region1`
    FOREIGN KEY (`Region_idregion`)
    REFERENCES `mydb`.`Region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comuna` (
  `idcom` INT NOT NULL COMMENT 'Primary key Id de la comuna',
  `nomcom` VARCHAR(75) NOT NULL COMMENT 'Nombre de la comuna',
  `Ciudad_idciu` INT NOT NULL COMMENT 'Foreing key tabla ciudad',
  PRIMARY KEY (`idcom`),
  INDEX `fk_Comuna_Ciudad1_idx` (`Ciudad_idciu` ASC),
  CONSTRAINT `fk_Comuna_Ciudad1`
    FOREIGN KEY (`Ciudad_idciu`)
    REFERENCES `mydb`.`Ciudad` (`idciu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoDireccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoDireccion` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `descTipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `iddirec` INT NOT NULL COMMENT 'Primary key tabla direccion',
  `direccion` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Nombre de la direccion de la empresa',
  `dept` TINYINT(1) NULL DEFAULT NULL COMMENT 'Vive en departamento si/no',
  `numdept` INT NULL DEFAULT NULL COMMENT 'numero departamento',
  `Empresa_idemp` INT(5) NOT NULL COMMENT 'Foreing key tabla empresa',
  `Comuna_idcom` INT NOT NULL COMMENT 'Foreing key tabla comuna',
  `TipoDireccion_idTipo` INT NOT NULL,
  PRIMARY KEY (`iddirec`),
  INDEX `fk_Direccion_Empresa1_idx` (`Empresa_idemp` ASC),
  INDEX `fk_Direccion_Comuna1_idx` (`Comuna_idcom` ASC),
  INDEX `fk_Direccion_TipoDireccion1_idx` (`TipoDireccion_idTipo` ASC),
  CONSTRAINT `fk_Direccion_Empresa1`
    FOREIGN KEY (`Empresa_idemp`)
    REFERENCES `mydb`.`Empresa` (`idemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direccion_Comuna1`
    FOREIGN KEY (`Comuna_idcom`)
    REFERENCES `mydb`.`Comuna` (`idcom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direccion_TipoDireccion1`
    FOREIGN KEY (`TipoDireccion_idTipo`)
    REFERENCES `mydb`.`TipoDireccion` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmprGeo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EmprGeo` (
  `idempgeo` INT NOT NULL AUTO_INCREMENT COMMENT 'Prymary key Id empresa geocalización',
  `latitud` FLOAT NULL COMMENT 'Parametros para la busqueda ',
  `longitud` FLOAT NULL DEFAULT NULL COMMENT 'Parametros para la busqueda',
  `Direccion_iddirec` INT NOT NULL,
  PRIMARY KEY (`idempgeo`),
  INDEX `fk_EmprGeo_Direccion1_idx` (`Direccion_iddirec` ASC),
  CONSTRAINT `fk_EmprGeo_Direccion1`
    FOREIGN KEY (`Direccion_iddirec`)
    REFERENCES `mydb`.`Direccion` (`iddirec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stock` (
  `totalpro` INT NOT NULL COMMENT 'Total numero de producto',
  `ultAct` DATE NOT NULL COMMENT 'Resto Producto',
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  `Empresa_idemp` INT(5) NOT NULL,
  `Cliente_idclie` INT(5) NOT NULL,
  PRIMARY KEY (`id_stock`),
  INDEX `fk_Stock_Empresa1_idx` (`Empresa_idemp` ASC),
  INDEX `fk_Stock_Cliente1_idx` (`Cliente_idclie` ASC),
  CONSTRAINT `fk_Stock_Empresa1`
    FOREIGN KEY (`Empresa_idemp`)
    REFERENCES `mydb`.`Empresa` (`idemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_Cliente1`
    FOREIGN KEY (`Cliente_idclie`)
    REFERENCES `mydb`.`Cliente` (`idclie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Familia` (
  `idFamilia` INT NOT NULL,
  `nomfam` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`idFamilia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SubFamilia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SubFamilia` (
  `idSubFamilia` INT NOT NULL COMMENT 'Primary key Tabla SubFamilia',
  `nomsubfam` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Nombre SubCategoria ',
  `Familia_idFamilia` INT NOT NULL COMMENT 'Foreing Key tabla famililia',
  PRIMARY KEY (`idSubFamilia`),
  INDEX `fk_SubFamilia_Familia1_idx` (`Familia_idFamilia` ASC),
  CONSTRAINT `fk_SubFamilia_Familia1`
    FOREIGN KEY (`Familia_idFamilia`)
    REFERENCES `mydb`.`Familia` (`idFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idproduc` INT(5) NOT NULL COMMENT 'Primary key tabla producto',
  `nomprod` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Nombre producto',
  `precio` DOUBLE NULL DEFAULT NULL COMMENT 'Precio producto',
  `descest` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Descripción de estado inactivo/activo',
  `SubFamilia_idSubFamilia` INT NOT NULL COMMENT 'Foreing key tabla subFamilia',
  `Estados_idest` INT(5) NOT NULL,
  `Stock_id_stock` INT NOT NULL,
  PRIMARY KEY (`idproduc`),
  INDEX `fk_Producto_SubFamilia1_idx` (`SubFamilia_idSubFamilia` ASC),
  INDEX `fk_Producto_Estados1_idx` (`Estados_idest` ASC),
  INDEX `fk_Producto_Stock1_idx` (`Stock_id_stock` ASC),
  CONSTRAINT `fk_Producto_SubFamilia1`
    FOREIGN KEY (`SubFamilia_idSubFamilia`)
    REFERENCES `mydb`.`SubFamilia` (`idSubFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Estados1`
    FOREIGN KEY (`Estados_idest`)
    REFERENCES `mydb`.`Estados` (`idest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Stock1`
    FOREIGN KEY (`Stock_id_stock`)
    REFERENCES `mydb`.`Stock` (`id_stock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visita` (
  `idVisita` INT NOT NULL COMMENT 'Primary key tabla visita',
  `numvisi` INT NULL DEFAULT NULL COMMENT 'AutoInscrementable de numero de visitar pagina empresa',
  `Empresa_idemp` INT(5) NOT NULL COMMENT 'Foreing Key Tabla Empresa',
  PRIMARY KEY (`idVisita`),
  INDEX `fk_Visita_Empresa_idx` (`Empresa_idemp` ASC),
  CONSTRAINT `fk_Visita_Empresa`
    FOREIGN KEY (`Empresa_idemp`)
    REFERENCES `mydb`.`Empresa` (`idemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa_has_Usuario` (
  `Empresa_idemp` INT(5) NOT NULL,
  `Usuario_idus` INT(5) NOT NULL,
  PRIMARY KEY (`Empresa_idemp`, `Usuario_idus`),
  INDEX `fk_Empresa_has_Usuario_Usuario1_idx` (`Usuario_idus` ASC),
  INDEX `fk_Empresa_has_Usuario_Empresa1_idx` (`Empresa_idemp` ASC),
  CONSTRAINT `fk_Empresa_has_Usuario_Empresa1`
    FOREIGN KEY (`Empresa_idemp`)
    REFERENCES `mydb`.`Empresa` (`idemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empresa_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idus`)
    REFERENCES `mydb`.`Usuario` (`idus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Precio` (
  `fechini` DATE NOT NULL,
  `fechfin` DATE NOT NULL,
  `precio` DOUBLE NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `Producto_idproduc` INT(5) NOT NULL,
  PRIMARY KEY (`id`, `Producto_idproduc`),
  INDEX `fk_Precio_Producto1_idx` (`Producto_idproduc` ASC),
  CONSTRAINT `fk_Precio_Producto1`
    FOREIGN KEY (`Producto_idproduc`)
    REFERENCES `mydb`.`Producto` (`idproduc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LogProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LogProducto` (
  `idLogProducto` INT NOT NULL AUTO_INCREMENT,
  `CantidadAntigua` INT NOT NULL,
  `CantidadNueva` INT NOT NULL,
  `FechaModificacion` DATE NOT NULL,
  `Cantidad` INT NOT NULL,
  `Producto_idproduc` INT(5) NOT NULL,
  PRIMARY KEY (`idLogProducto`),
  INDEX `fk_LogProducto_Producto1_idx` (`Producto_idproduc` ASC),
  CONSTRAINT `fk_LogProducto_Producto1`
    FOREIGN KEY (`Producto_idproduc`)
    REFERENCES `mydb`.`Producto` (`idproduc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
