-- MySQL Script generated by MySQL Workbench
-- 11/26/14 12:28:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `idpais` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key Id del pais',
  `nompais` VARCHAR(45) NOT NULL COMMENT 'Nombre pais',
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `idregion` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key Id de la region',
  `nomregion` VARCHAR(75) NULL DEFAULT NULL COMMENT 'Nombre de la region',
  `Pais_idpais` INT(11) NOT NULL COMMENT 'Foreing key tabla pais',
  PRIMARY KEY (`idregion`),
  INDEX `fk_Region_Pais1_idx` (`Pais_idpais` ASC),
  CONSTRAINT `fk_Region_Pais1`
    FOREIGN KEY (`Pais_idpais`)
    REFERENCES `mydb`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ciudad` (
  `idciu` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key Id de la ciudad',
  `nomciu` VARCHAR(75) NULL DEFAULT NULL COMMENT 'Nombre de la ciudad',
  `Region_idregion` INT(11) NOT NULL COMMENT 'Foreing key tabla region',
  PRIMARY KEY (`idciu`),
  INDEX `fk_Ciudad_Region1_idx` (`Region_idregion` ASC),
  CONSTRAINT `fk_Ciudad_Region1`
    FOREIGN KEY (`Region_idregion`)
    REFERENCES `mydb`.`region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idclie` INT(5) NOT NULL AUTO_INCREMENT COMMENT 'Primary key tabla ClienteId',
  `rut` INT(8) NULL DEFAULT NULL COMMENT 'Rut cliente',
  `dv` CHAR(1) NULL DEFAULT NULL COMMENT 'Dígito verificador cliente',
  `nomb` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Nombres de cliente',
  `apells` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Apellidos del cliente',
  `fenac` DATE NULL DEFAULT NULL COMMENT 'Fecha nacimiento del cliente',
  `fevalde` DATE NULL DEFAULT NULL COMMENT 'Fecha de activación del cliente',
  `Correo` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Correo electronico Cliente',
  PRIMARY KEY (`idclie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comuna` (
  `idcom` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key Id de la comuna',
  `nomcom` VARCHAR(75) NOT NULL COMMENT 'Nombre de la comuna',
  `Ciudad_idciu` INT(11) NOT NULL COMMENT 'Foreing key tabla ciudad',
  PRIMARY KEY (`idcom`),
  INDEX `fk_Comuna_Ciudad1_idx` (`Ciudad_idciu` ASC),
  CONSTRAINT `fk_Comuna_Ciudad1`
    FOREIGN KEY (`Ciudad_idciu`)
    REFERENCES `mydb`.`ciudad` (`idciu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `idemp` INT(5) NOT NULL AUTO_INCREMENT COMMENT 'Primary key ID de la empresa',
  `rutemp` INT(8) NULL DEFAULT NULL COMMENT 'Numero identificador de la empresa rut',
  `dvemp` CHAR(1) NULL DEFAULT NULL COMMENT 'Dígito verificador Empresa',
  `nomb` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Nombre Empresa',
  `fenac` DATE NULL DEFAULT NULL COMMENT 'Fecha de inicio de actividades',
  `fevalde` DATE NULL DEFAULT NULL COMMENT 'Fecha de activación empresa en el sistema',
  `Cliente_idclie` INT(5) NOT NULL COMMENT 'Foreing key tabla cliente',
  PRIMARY KEY (`idemp`),
  INDEX `fk_Empresa_Cliente1_idx` (`Cliente_idclie` ASC),
  CONSTRAINT `fk_Empresa_Cliente1`
    FOREIGN KEY (`Cliente_idclie`)
    REFERENCES `mydb`.`cliente` (`idclie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direccion` (
  `iddirec` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key tabla direccion',
  `direccion` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Nombre de la direccion de la empresa',
  `num` INT(11) NULL DEFAULT NULL COMMENT 'Numeracion',
  `dept` TINYINT(1) NULL DEFAULT NULL COMMENT 'Vive en departamento si/no',
  `numdept` INT(11) NULL DEFAULT NULL COMMENT 'numero departamento',
  `Empresa_idemp` INT(5) NOT NULL COMMENT 'Foreing key tabla empresa',
  `Comuna_idcom` INT(11) NOT NULL COMMENT 'Foreing key tabla comuna',
  PRIMARY KEY (`iddirec`),
  INDEX `fk_Direccion_Empresa1_idx` (`Empresa_idemp` ASC),
  INDEX `fk_Direccion_Comuna1_idx` (`Comuna_idcom` ASC),
  CONSTRAINT `fk_Direccion_Comuna1`
    FOREIGN KEY (`Comuna_idcom`)
    REFERENCES `mydb`.`comuna` (`idcom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direccion_Empresa1`
    FOREIGN KEY (`Empresa_idemp`)
    REFERENCES `mydb`.`empresa` (`idemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `idest` INT(5) NOT NULL AUTO_INCREMENT COMMENT 'Primary key Id estado',
  `nomest` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Nombre de estado',
  `descest` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Descripcion  del estado',
  PRIMARY KEY (`idest`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idus` INT(5) NOT NULL AUTO_INCREMENT COMMENT 'Primary key tabla usuario',
  `usernom` VARCHAR(8) NULL DEFAULT NULL COMMENT 'Nombre Usuario para acceder',
  `cod` VARCHAR(8) NULL DEFAULT NULL COMMENT 'Clave de usuario para acceder',
  `nomb` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Nombres del usuario',
  `Apells` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Apellidos del Usuario',
  `fecrea` DATE NULL DEFAULT NULL COMMENT 'Fecha de creación del Usuario',
  `fevalha` DATE NULL DEFAULT NULL COMMENT 'Fecha de expiración de cuenta',
  `Estados_idest` INT(5) NOT NULL COMMENT 'Foring key yalba estados',
  PRIMARY KEY (`idus`),
  INDEX `fk_Usuario_Estados1_idx` (`Estados_idest` ASC),
  CONSTRAINT `fk_Usuario_Estados1`
    FOREIGN KEY (`Estados_idest`)
    REFERENCES `mydb`.`estados` (`idest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`empresa_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa_has_usuario` (
  `Empresa_idemp` INT(5) NOT NULL AUTO_INCREMENT,
  `Usuario_idus` INT(5) NOT NULL,
  PRIMARY KEY (`Empresa_idemp`, `Usuario_idus`),
  INDEX `fk_Empresa_has_Usuario_Usuario1_idx` (`Usuario_idus` ASC),
  INDEX `fk_Empresa_has_Usuario_Empresa1_idx` (`Empresa_idemp` ASC),
  CONSTRAINT `fk_Empresa_has_Usuario_Empresa1`
    FOREIGN KEY (`Empresa_idemp`)
    REFERENCES `mydb`.`empresa` (`idemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empresa_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idus`)
    REFERENCES `mydb`.`usuario` (`idus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`emprgeo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprgeo` (
  `idempgeo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Prymary key Id empresa geocalización',
  `latitud` FLOAT NULL DEFAULT NULL COMMENT 'Parametros para la busqueda ',
  `longitud` FLOAT NULL DEFAULT NULL COMMENT 'Parametros para la busqueda',
  `Empresa_idemp` INT(5) NOT NULL COMMENT 'Foreing key tabla empresa',
  `tipo` VARCHAR(75) NULL COMMENT 'Casa/Comercio/varios(Clasificacion)',
  PRIMARY KEY (`idempgeo`),
  INDEX `fk_EmprGeo_Empresa1_idx` (`Empresa_idemp` ASC),
  CONSTRAINT `fk_EmprGeo_Empresa1`
    FOREIGN KEY (`Empresa_idemp`)
    REFERENCES `mydb`.`empresa` (`idemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`familia` (
  `idFamilia` INT(11) NOT NULL AUTO_INCREMENT,
  `nomfam` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`idFamilia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`subfamilia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subfamilia` (
  `idSubFamilia` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key Tabla SubFamilia',
  `nomsubfam` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Nombre SubCategoria ',
  `Familia_idFamilia` INT(11) NOT NULL COMMENT 'Foreing Key tabla famililia',
  PRIMARY KEY (`idSubFamilia`),
  INDEX `fk_SubFamilia_Familia1_idx` (`Familia_idFamilia` ASC),
  CONSTRAINT `fk_SubFamilia_Familia1`
    FOREIGN KEY (`Familia_idFamilia`)
    REFERENCES `mydb`.`familia` (`idFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idproduc` INT(5) NOT NULL AUTO_INCREMENT COMMENT 'Primary key tabla producto',
  `nomprod` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Nombre producto',
  `precio` DOUBLE NULL DEFAULT NULL COMMENT 'Precio producto',
  `Empresa_idemp` INT(5) NOT NULL COMMENT 'Foreing keey talba empresa',
  `SubFamilia_idSubFamilia` INT(11) NOT NULL COMMENT 'Foreing key tabla subFamilia',
  `estados_idest` INT(5) NOT NULL,
  PRIMARY KEY (`idproduc`),
  INDEX `fk_Producto_Empresa1_idx` (`Empresa_idemp` ASC),
  INDEX `fk_Producto_SubFamilia1_idx` (`SubFamilia_idSubFamilia` ASC),
  INDEX `fk_producto_estados1_idx` (`estados_idest` ASC),
  CONSTRAINT `fk_Producto_Empresa1`
    FOREIGN KEY (`Empresa_idemp`)
    REFERENCES `mydb`.`empresa` (`idemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_SubFamilia1`
    FOREIGN KEY (`SubFamilia_idSubFamilia`)
    REFERENCES `mydb`.`subfamilia` (`idSubFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_estados1`
    FOREIGN KEY (`estados_idest`)
    REFERENCES `mydb`.`estados` (`idest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock` (
  `idstock` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key tabla Stock',
  `totalpro` INT(11) NULL DEFAULT NULL COMMENT 'Total numero de producto',
  `restpro` INT(11) NULL DEFAULT NULL COMMENT 'Resto Producto',
  `producto_idproduc` INT(5) NOT NULL,
  PRIMARY KEY (`idstock`),
  INDEX `fk_stock_producto1_idx` (`producto_idproduc` ASC),
  CONSTRAINT `fk_stock_producto1`
    FOREIGN KEY (`producto_idproduc`)
    REFERENCES `mydb`.`producto` (`idproduc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visita` (
  `idVisita` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key tabla visita',
  `numvisi` INT(11) NULL DEFAULT NULL COMMENT 'AutoInscrementable de numero de visitar pagina empresa',
  `Empresa_idemp` INT(5) NOT NULL COMMENT 'Foreing Key Tabla Empresa',
  PRIMARY KEY (`idVisita`),
  INDEX `fk_Visita_Empresa_idx` (`Empresa_idemp` ASC),
  CONSTRAINT `fk_Visita_Empresa`
    FOREIGN KEY (`Empresa_idemp`)
    REFERENCES `mydb`.`empresa` (`idemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
